ALTER TABLE "challenges"
ADD COLUMN IF NOT EXISTS "startTime" TEXT NOT NULL DEFAULT '09:30',
ADD COLUMN IF NOT EXISTS "roundsCount" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN IF NOT EXISTS "lanes25Count" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN IF NOT EXISTS "lanes50Count" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "isArchived" BOOLEAN NOT NULL DEFAULT false;

UPDATE "challenges"
SET "isActive" = true
WHERE "id" IN (
  SELECT "id"
  FROM "challenges"
  ORDER BY "createdAt" ASC
  LIMIT 1
)
AND NOT EXISTS (SELECT 1 FROM "challenges" WHERE "isActive" = true);
